import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { auth } from "@clerk/nextjs/server";
import { Suspense } from "react";
import Loading from "./loading"
import { SignIn } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = auth().userId; // Fetch user information
  !user && auth().redirectToSignIn()
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading/>}>
          <ConvexClientProvider>
          {children}
          </ConvexClientProvider>
          </Suspense>
        </body>
    </html>
  );
}
